import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import SearchBar from '../components/SearchBar'
import BookGrid from '../components/BookGrid'

const Home: NextPage = () => {
  const handleSearch = (search: string) => {
    console.log(search)
  }

  return (
    <div className="p-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1 className="text-3xl font-bold underline">Some Title Here</h1>
        <SearchBar onSearch={handleSearch} />
      </header>
      <main>
        <BookGrid />
      </main>
    </div>
  )
}

export default Home
